package io.openledger


object LedgerError extends Enumeration {
  type LedgerError = Value
  val DEBIT_ACCOUNT_INSUFFICIENT_AVAILABLE, CREDIT_ACCOUNT_INSUFFICIENT_AVAILABLE, INSUFFICIENT_AUTHORIZED_BALANCE, CAPTURE_MORE_THAN_AUTHORIZED = Value
}
