package io.openledger

object LedgerError extends Enumeration {
  type LedgerError = Value
  val UNSUPPORTED_ACCOUNT_OPERATION_ON_CURRENT_STATE, DEBIT_ACCOUNT_INSUFFICIENT_AVAILABLE,
      CREDIT_ACCOUNT_INSUFFICIENT_AVAILABLE, INSUFFICIENT_AUTHORIZED_BALANCE, CAPTURE_MORE_THAN_AUTHORIZED,
      UNSUPPORTED_ENTRY_OPERATION_ON_CURRENT_STATE, INTERNAL_ERROR, COMMAND_THROTTLED = Value
}
